justbballstuff/defense_synergy/urls.py
from django.urls import path
from . import views

app_name = 'defense_synergy'

urlpatterns = [
    path('total/', views.TotalDefensiveSynergyView.as_view(), name='total'),
    path('per-game/', views.PerGameDefensiveSynergyView.as_view(), name='per_game'),
    path('per-36/', views.PerMinDefensiveSynergyView.as_view(), name='per_min'),
    path('summary/', views.SummaryDefensiveSynergyView.as_view(), name='summary'),
    path('glossary/', views.glossary, name='glossary'),
]

justbballstuff/justbballstuff/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('profiles/', include('player_profile.urls')),
    path('matchups/', include('matchups.urls')),
    path('defensive-playmaking/', include('defensive_playmaking.urls')),
    path('rim-protection/', include('rim_protection.urls')),
    path('defensive-synergy/', include('defense_synergy.urls')),
    path('defensive-rebounding/', include('defensive_rebounding.urls')),
]

justbballstuff/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('matchups/', include('matchups.urls')),
    path('defensive-playmaking/', include('defensive_playmaking.urls')),
    path('defensive-synergy/', include('defense_synergy.urls')),
    path('rim-protection/', include('rim_protection.urls')),
    path('defensive-rebounding/', include('defensive_rebounding.urls')),
]

justbballstuff/defense_synergy/models.py
from django.db import models

# Create your models here.
class DefensiveSynergyStat(models.Model):
    player = models.CharField(max_length=120, blank=False)
    season = models.CharField(max_length=10, blank=False)
    team = models.CharField(max_length=3)
    age = models.IntegerField(default=0)
    height_in = models.IntegerField(default=0)
    weight_lb = models.IntegerField(default=0)
    games_played = models.IntegerField(default=0)
    minutes_played = models.IntegerField(default=0)
    isolation_poss = models.IntegerField(default=0)
    isolation_pts = models.IntegerField(default=0)
    isolation_percentile = models.FloatField(default=0.0)
    isolation_ppp = models.FloatField(default=0.0)
    isolation_freq = models.FloatField(default=0.0)
    ball_handler_poss = models.IntegerField(default=0)
    ball_handler_pts = models.IntegerField(default=0)
    ball_handler_percentile = models.FloatField(default=0.0)
    ball_handler_ppp = models.FloatField(default=0.0)
    ball_handler_freq = models.FloatField(default=0.0)
    roll_man_poss = models.IntegerField(default=0)
    roll_man_pts = models.IntegerField(default=0)
    roll_man_percentile = models.FloatField(default=0.0)
    roll_man_ppp = models.FloatField(default=0.0)
    roll_man_freq = models.FloatField(default=0.0)
    post_up_poss = models.IntegerField(default=0)
    post_up_pts = models.IntegerField(default=0)
    post_up_percentile = models.FloatField(default=0.0)
    post_up_ppp = models.FloatField(default=0.0)
    post_up_freq = models.FloatField(default=0.0)
    spot_up_poss = models.IntegerField(default=0)
    spot_up_pts = models.IntegerField(default=0)
    spot_up_percentile = models.FloatField(default=0.0)
    spot_up_ppp = models.FloatField(default=0.0)
    spot_up_freq = models.FloatField(default=0.0)
    hand_off_poss = models.IntegerField(default=0)
    hand_off_pts = models.IntegerField(default=0)
    hand_off_percentile = models.FloatField(default=0.0)
    hand_off_ppp = models.FloatField(default=0.0)
    hand_off_freq = models.FloatField(default=0.0)
    off_screen_poss = models.IntegerField(default=0)
    off_screen_pts = models.IntegerField(default=0)
    off_screen_percentile = models.FloatField(default=0.0)
    off_screen_ppp = models.FloatField(default=0.0)
    off_screen_freq = models.FloatField(default=0.0)


    class Meta:
        unique_together = ('player', 'season')

    def get_height(self):
        return f"{int(self.height_in / 12)}'{self.height_in % 12}"

    def __str__(self):
        return f"{self.player} : {self.season}"

justbballstuff/defense_synergy/views.py
from django.shortcuts import render
from .tables import TotalDefensiveSynergyTable, PerGameDefensiveSynergyTable, PerMinDefensiveSynergyTable, SummaryDefensiveSynergyTable
from .filters import DefensiveSynergyFilter
from .models import DefensiveSynergyStat
from django_tables2 import SingleTableMixin
from django_filters.views import FilterView

# Create your views here.
class TotalDefensiveSynergyView(SingleTableMixin, FilterView):
    model = DefensiveSynergyStat
    table_class = TotalDefensiveSynergyTable
    template_name = 'defense_synergy/table.html'
    filterset_class = DefensiveSynergyFilter
    extra_context={'title_head': "Defensive Synergy: Total", "defense_synergy": True, "total": True}

class PerGameDefensiveSynergyView(SingleTableMixin, FilterView):
    model = DefensiveSynergyStat
    table_class = PerGameDefensiveSynergyTable
    template_name = 'defense_synergy/table.html'
    filterset_class = DefensiveSynergyFilter
    extra_context={'title_head': "Defensive Synergy: Per Game", "defense_synergy": True, "per_game": True}

class PerMinDefensiveSynergyView(SingleTableMixin, FilterView):
    model = DefensiveSynergyStat
    table_class = PerMinDefensiveSynergyTable
    template_name = 'defense_synergy/table.html'
    filterset_class = DefensiveSynergyFilter
    extra_context={'title_head': "Defensive Synergy: Per 36 Mins", "defense_synergy": True, "per_min": True}

class SummaryDefensiveSynergyView(SingleTableMixin, FilterView):
    model = DefensiveSynergyStat
    table_class = SummaryDefensiveSynergyTable
    template_name = 'defense_synergy/table.html'
    filterset_class = DefensiveSynergyFilter
    extra_context={'title_head': "Defensive Synergy: Summary", "defense_synergy": True, "summary": True}

def glossary(request):
    return render(request, 'defense_synergy/glossary.html', {'title_head': "Defensive Synergy: Glossary", "defense_synergy": True, "glossary": True})

justbballstuff/defense_synergy/templates/defense_synergy/base.html
{% extends 'justbballstuff/base.html' %}

{% block menu %}
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link {% if total %}active{% endif %}" href="{% url 'defense_synergy:total' %}">Total</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if per_game %}active{% endif %}" href="{% url 'defense_synergy:per_game' %}">Per Game</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if per_min %}active{% endif %}" href="{% url 'defense_synergy:per_min' %}">Per 36</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if summary %}active{% endif %}" href="{% url 'defense_synergy:summary' %}">Summary</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if glossary %}active{% endif %}" href="{% url 'defense_synergy:glossary' %}">Glossary</a>
      </li>
    </ul>
  </nav>
{% endblock %}

{% block content %}
{% endblock %}

justbballstuff/defense_synergy/templates/defense_synergy/filter.html
{% load bootstrap4 %}

{% if filter %}
  <form method="get">
    <div class='row'>
      <div class="form-group col-sm-4 col-md-4">
        <h4 style="margin-top: 0">Player/Team/Season</h4>
        {% bootstrap_field filter.form.player %}
        {% bootstrap_field filter.form.team %}
        {% bootstrap_field filter.form.season %}
      </div>
      <div class="form-group col-sm-4 col-md-4">
        <h4 style="margin-top: 0">Age/Height/Weight</h4>
        {% bootstrap_field filter.form.age %}
        {% bootstrap_field filter.form.height_in %}
        {% bootstrap_field filter.form.weight_lb %}
      </div>
      <div class="form-group col-sm-4 col-md-4">
        <h4 style="margin-top: 0">Playing Time</h4>
        {% bootstrap_field filter.form.games_played %}
        {% bootstrap_field filter.form.minutes_played %}
      </div>
    </div>
    <div class="form-group btn">
    {% bootstrap_button 'filter' %}
    </div>
  </form>
{% endif %}

justbballstuff/defense_synergy/templates/defense_synergy/glossary.html
{% extends "defense_synergy/base.html" %}

{% block content %}
  <h1 class='display-4'>Glossary</h1>
  <p class="alert alert-danger">Please Note: Defensive Synergy stats are better equipped to describe role and what type of scoring possessions players most frequently defend.  There is also a lot of noise to the stats used here. Pick n Roll ball handler and screener point per possession stats can be influenced by the type of defensive coverage (drop vs a more aggressive scheme).  Spot-up can be influenced by how aggressive the help defense is.  Plus there is also just a lot of noise in these stats due to the fact that these stats don't capture matchup difficulty or deterence.  These stats are also vulnerable to the small sample/make-or-miss nature of the league.  So use these stats with care and caution.</p>

  <p>Stats are provided in:</p>
  <ul>
    <li>Season Totals</li>
    <li>Per Games</li>
    <li>Per 36 Minutes</li>
    <li>Summary</li>
  </ul>
  <table class="table table-striped">
    <tr>
      <th>PLAYER</th>
      <td>Name of the Player</td>
    </tr>
    <tr>
      <th>TEAM</th>
      <td>Acronym of Team of the Player<br>TEAM is whatever team the player finished the season with (according to https://www.nba.com/stats/players/bio/ at least).</td>
    </tr>
    <tr>
      <th>AGE</th>
      <td>Age of the Player at the Start of that Season</td>
    </tr>
    <tr>
      <th>HEIGHT</th>
      <td>Height of the Player in feet and inches</td>
    </tr>
    <tr>
      <th>WEIGHT</th>
      <td>Weight of the Player in pounds</td>
    </tr>
    <tr>
      <th>SEASON</th>
      <td>Regular Season</td>
    </tr>
    <tr>
      <th>GP</th>
      <td>the Number of Games Played in that Season</td>
    </tr>
    <tr>
      <th>MP</th>
      <td>the Number of Minutes Played in that Season</td>
    </tr>
    <tr>
      <th>Iso Poss</th>
      <td>the number of isolation possessions (that ended in a FGA, FTA(s), or TOV from the iso player) defended by the player</td>
    </tr>
    <tr>
      <th>Iso PPP</th>
      <td>the number of points per possession allowed when defending the iso possession</td>
    </tr>
    <tr>
      <th>Iso Freq%</th>
      <td>isolation possessions defended divided by total possessions</td>
    </tr>
    <tr>
      <th>Iso Percentile</th>
      <td>the percentile ranking of Iso PPP</td>
    </tr>
    <tr>
      <th>PnR BH Poss</th>
      <td>the number of pick n roll possessions (that ended in a FGA, FTA(s), or TOV from the pick n roll ball handler) defended by the player</td>
    </tr>
    <tr>
      <th>PnR BH PPP</th>
      <td>the number of points per possession allowed when defending the pick n roll ball handler</td>
    </tr>
    <tr>
      <th>PnR BH Freq%</th>
      <td>pick n roll ball-handler possessions defended divided by total possessions</td>
    </tr>
    <tr>
      <th>PnR BH Percentile</th>
      <td>the percentile ranking of PnR BH PPP</td>
    </tr>
    <tr>
      <th>PnR Screener Poss</th>
      <td>the number of pick n roll possessions (that ended in a FGA, FTA(s), or TOV from the pick n roll screener) defended by the player</td>
    </tr>
    <tr>
      <th>PnR Screener PPP</th>
      <td>the number of points per possession allowed when defending the pick n roll screener</td>
    </tr>
    <tr>
      <th>PnR Screener Freq%</th>
      <td>pick n roll screener possessions defended divided by total possessions</td>
    </tr>
    <tr>
      <th>PnR Screener Percentile</th>
      <td>the percentile ranking of PnR Screener PPP</td>
    </tr>
    <tr>
      <th>Post-up Poss</th>
      <td>the number of post-up possessions (that ended in a FGA, FTA(s), or TOV from the post player) defended by the player</td>
    </tr>
    <tr>
      <th>Post-up PPP</th>
      <td>the number of points per possession allowed when defending the post up</td>
    </tr>
    <tr>
      <th>Post-up Freq%</th>
      <td>post up possessions defended divided by total possessions</td>
    </tr>
    <tr>
      <th>Post-up Percentile</th>
      <td>the percentile ranking of Post-up PPP</td>
    </tr>
    <tr>
      <th>Spot-up Poss</th>
      <td>the number of spot-up possessions (that ended in a FGA, FTA(s), or TOV from the spot up player) defended by the player</td>
    </tr>
    <tr>
      <th>Spot-up PPP</th>
      <td>the number of points per possession allowed when defending the spot up</td>
    </tr>
    <tr>
      <th>Spot-up Freq%</th>
      <td>spot-up possessions defended divided by total possessions</td>
    </tr>
    <tr>
      <th>Spot-up Percentile</th>
      <td>the percentile ranking of Spot-up PPP</td>
    </tr>
    <tr>
      <th>Hand-off Poss</th>
      <td>the number of hand-off possessions (that ended in a FGA, FTA(s), or TOV from the hand-off ball handler) defended by the player</td>
    </tr>
    <tr>
      <th>Hand-off PPP</th>
      <td>the number of points per possession allowed when defending the hand-off sets</td>
    </tr>
    <tr>
      <th>Hand-off Freq%</th>
      <td>hand-off possessions defended divided by total possessions</td>
    </tr>
    <tr>
      <th>Hand-off Percentile</th>
      <td>the percentile ranking of Hand-off PPP</td>
    </tr>
    <tr>
      <th>Off-Screen Poss</th>
      <td>the number of off-screen possessions (that ended in a FGA, FTA(s), or TOV from the off screen shooter) defended by the player</td>
    </tr>
    <tr>
      <th>Off-Screen PPP</th>
      <td>the number of points per possession allowed when defending the off-screen possession</td>
    </tr>
    <tr>
      <th>Off-Screen Freq%</th>
      <td>off-screen possessions defended divided by total possessions</td>
    </tr>
    <tr>
      <th>Off-Screen Percentile</th>
      <td>the percentile ranking of Off-Screen PPP</td>
    </tr>
  </table>
{% endblock %}

justbballstuff/defense_synergy/templates/defense_synergy/table.html
{% extends "defense_synergy/base.html" %}
{% load render_table from django_tables2 %}
{% load bootstrap4 %}

{% block content %}
  <h4 class='display-4'>{{ title_head }}</h4>
  <p>Get all the defensive playtype data from synergy that has taken place since 2017-18.  Playtypes include isolations, pick n roll ball handlers, pick n roll screeners, spot-ups, post-ups, hand-offs, and off-screens.  Stats include possessions, points per possessions, frequency of play-type, and percentile rank for points per possessions.</p>
  {% include 'defense_synergy/filter.html' %}
  {% render_table table %}
{% endblock %}