justbballstuff/defensive_rebounding/urls.py
from django.urls import path
from . import views

app_name = 'defensive_rebounding'

urlpatterns = [
    path('total/', views.TotalReboundingView.as_view(), name='total'),
    path('per-game/', views.PerGameReboundingView.as_view(), name='per_game'),
    path('per-36/', views.PerMinReboundingView.as_view(), name='per_min'),
    path('glossary/', views.glossary, name='glossary'),
]

justbballstuff/justbballstuff/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('profiles/', include('player_profile.urls')),
    path('matchups/', include('matchups.urls')),
    path('defensive-playmaking/', include('defensive_playmaking.urls')),
    path('rim-protection/', include('rim_protection.urls')),
    path('defensive-synergy/', include('defense_synergy.urls')),
    path('defensive-rebounding/', include('defensive_rebounding.urls')),
]

justbballstuff/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('matchups/', include('matchups.urls')),
    path('defensive-playmaking/', include('defensive_playmaking.urls')),
    path('defensive-synergy/', include('defense_synergy.urls')),
    path('rim-protection/', include('rim_protection.urls')),
    path('defensive-rebounding/', include('defensive_rebounding.urls')),
]

justbballstuff/defensive_rebounding/models.py
from django.db import models

# Create your models here.
class ReboundingStat(models.Model):
    player = models.CharField(max_length=120, blank=False)
    season = models.CharField(max_length=10, blank=False)
    team = models.CharField(max_length=3)
    age = models.IntegerField(default=0)
    height_in = models.IntegerField(default=0)
    weight_lb = models.IntegerField(default=0)
    games_played = models.IntegerField(default=0)
    minutes_played = models.IntegerField(default=0)
    dreb = models.IntegerField(default=0)
    dboxout = models.IntegerField(default=0)
    dreb_rank = models.FloatField(default=0.0)
    dboxout_rank = models.FloatField(default=0.0)
    dreb_per_game = models.FloatField(default=0.0)
    dboxout_per_game = models.FloatField(default=0.0)
    dreb_rank_per_game = models.FloatField(default=0.0)
    dboxout_rank_per_game = models.FloatField(default=0.0)
    dreb_per_min = models.FloatField(default=0.0)
    dboxout_per_min = models.FloatField(default=0.0)
    dreb_rank_per_min = models.FloatField(default=0.0)
    dboxout_rank_per_min = models.FloatField(default=0.0)


    class Meta:
        unique_together = ('player', 'season')

    def get_height(self):
        return f"{int(self.height_in / 12)}'{self.height_in % 12}"

    def __str__(self):
        return f"{self.player} : {self.season}"

justbballstuff/defensive_rebounding/views.py
from django.shortcuts import render
from .tables import TotalReboundingTable, PerGameReboundingTable, PerMinReboundingTable
from .filters import ReboundingFilter
from .models import ReboundingStat
from django_tables2 import SingleTableMixin
from django_filters.views import FilterView

# Create your views here.
class TotalReboundingView(SingleTableMixin, FilterView):
    model = ReboundingStat
    table_class = TotalReboundingTable
    template_name = 'defensive_rebounding/table.html'
    filterset_class = ReboundingFilter
    extra_context={'title_head': "Defensive Rebounding: Total", "defensive_rebounding": True, "total": True}

class PerGameReboundingView(SingleTableMixin, FilterView):
    model = ReboundingStat
    table_class = PerGameReboundingTable
    template_name = 'defensive_rebounding/table.html'
    filterset_class = ReboundingFilter
    extra_context={'title_head': "Defensive Rebounding: Per Game", "defensive_rebounding": True, "per_game": True}

class PerMinReboundingView(SingleTableMixin, FilterView):
    model = ReboundingStat
    table_class = PerMinReboundingTable
    template_name = 'defensive_rebounding/table.html'
    filterset_class = ReboundingFilter
    extra_context={'title_head': "Defensive Rebounding: Per 36 Mins", "defensive_rebounding": True, "per_min": True}

def glossary(request):
    return render(request, 'defensive_rebounding/glossary.html', {'title_head': "Defensive Rebounding: Glossary", "defensive_rebounding": True, "glossary": True})

justbballstuff/defensive_rebounding/templates/defensive_rebounding/base.html
{% extends 'justbballstuff/base.html' %}

{% block menu %}
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link {% if total %}active{% endif %}" href="{% url 'defensive_rebounding:total' %}">Total</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if per_game %}active{% endif %}" href="{% url 'defensive_rebounding:per_game' %}">Per Game</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if per_min %}active{% endif %}" href="{% url 'defensive_rebounding:per_min' %}">Per 36</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if glossary %}active{% endif %}" href="{% url 'defensive_rebounding:glossary' %}">Glossary</a>
      </li>
    </ul>
  </nav>
{% endblock %}

{% block content %}
{% endblock %}

justbballstuff/defensive_rebounding/templates/defensive_rebounding/filters.html
{% load bootstrap4 %}

{% if filter %}
  <form method="get">
    <div class='row'>
      <div class="form-group col-sm-4 col-md-4">
        <h4 style="margin-top: 0">Player/Team/Season</h4>
        {% bootstrap_field filter.form.player %}
        {% bootstrap_field filter.form.team %}
        {% bootstrap_field filter.form.season %}
      </div>
      <div class="form-group col-sm-4 col-md-4">
        <h4 style="margin-top: 0">Age/Height/Weight</h4>
        {% bootstrap_field filter.form.age %}
        {% bootstrap_field filter.form.height_in %}
        {% bootstrap_field filter.form.weight_lb %}
      </div>
      <div class="form-group col-sm-4 col-md-4">
        <h4 style="margin-top: 0">Playing Time</h4>
        {% bootstrap_field filter.form.games_played %}
        {% bootstrap_field filter.form.minutes_played %}
      </div>
    </div>
    <div class="form-group btn">
    {% bootstrap_button 'filter' %}
    </div>
  </form>
{% endif %}

justbballstuff/defensive_rebounding/templates/defensive_rebounding/glossary.html
{% extends "defensive_rebounding/base.html" %}

{% block content %}
  <h1 class='display-4'>Glossary</h1>
  <p>Stats are provided in:</p>
  <ul>
    <li>Season Totals</li>
    <li>Per Games</li>
    <li>Per 36 Minutes</li>
  </ul>
  <table class="table table-striped">
    <tr>
      <th>PLAYER</th>
      <td>Name of the Player</td>
    </tr>
    <tr>
      <th>TEAM</th>
      <td>Acronym of Team of the Player<br>TEAM is whatever team the player finished the season with (according to https://www.nba.com/stats/players/bio/ at least).</td>
    </tr>
    <tr>
      <th>AGE</th>
      <td>Age of the Player at the Start of that Season</td>
    </tr>
    <tr>
      <th>HEIGHT</th>
      <td>Height of the Player in feet and inches</td>
    </tr>
    <tr>
      <th>WEIGHT</th>
      <td>Weight of the Player in pounds</td>
    </tr>
    <tr>
      <th>SEASON</th>
      <td>Regular Season</td>
    </tr>
    <tr>
      <th>GP</th>
      <td>the Number of Games Played in that Season</td>
    </tr>
    <tr>
      <th>MP</th>
      <td>the Number of Minutes Played in that Season</td>
    </tr>
    <tr>
      <th>DREB</th>
      <td>the Number of Defensive Rebounds in that Season</td>
    </tr>
    <tr>
      <th>DEF BOX OUT</th>
      <td>The number of times a player made physical contact with an opponent who was actively pursuing a rebound, showed visible progress or strong effort in disadvantaging the opponent, and successfully prevented that opponent from securing the rebound</td>
    </tr>
    <tr>
      <th>DREB RANK</th>
      <td>the Percentile Rank of Defensive Rebounds for Players that Played at least 500 minutes</td>
    </tr>
    <tr>
      <th>DEF BOX OUT RANK</th>
      <td>the Percentile Rank of Defensive Box Outs for Players that Played at least 500 minutes</td>
    </tr>
  </table>
{% endblock %}

justbballstuff/defensive_rebounding/templates/defensive_rebounding/table.html
{% extends "defensive_rebounding/base.html" %}
{% load render_table from django_tables2 %}
{% load bootstrap4 %}

{% block content %}
  <h4 class='display-4'>{{ title_head }}</h4>
  <p>Get Defensive Rebounds and Defensive Boxouts since 2017-18 for every player.  Stats come in Total, Per Game, and Per 36 Minutes, alonged with rank percentiles for players who played at least 500 minutes.</p>
  {% include 'defensive_rebounding/filters.html' %}
  {% render_table table %}
{% endblock %}