justbballstuff/defensive_playmaking/urls.py
from django.urls import path
from . import views

app_name = 'defensive_playmaking'

urlpatterns = [
    path('total/', views.TotalDefensivePlaymakingView.as_view(), name='total'),
    path('per-game/', views.PerGameDefensivePlaymakingView.as_view(), name='per_game'),
    path('per-36/', views.PerMinDefensivePlaymakingView.as_view(), name='per_min'),
    path('rank-per-game/', views.RankPerGameDefensivePlaymakingView.as_view(), name='rank_per_game'),
    path('rank-per-min/', views.RankPerMinDefensivePlaymakingView.as_view(), name='rank_per_min'),
    path('glossary/', views.glossary, name='glossary'),
]

justbballstuff/justbballstuff/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('profiles/', include('player_profile.urls')),
    path('matchups/', include('matchups.urls')),
    path('defensive-playmaking/', include('defensive_playmaking.urls')),
    path('rim-protection/', include('rim_protection.urls')),
    path('defensive-synergy/', include('defense_synergy.urls')),
    path('defensive-rebounding/', include('defensive_rebounding.urls')),
]

justbballstuff/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('matchups/', include('matchups.urls')),
    path('defensive-playmaking/', include('defensive_playmaking.urls')),
    path('defensive-synergy/', include('defense_synergy.urls')),
    path('rim-protection/', include('rim_protection.urls')),
    path('defensive-rebounding/', include('defensive_rebounding.urls')),
]

justbballstuff/defensive_playmaking/models.py
from django.db import models

# Create your models here.
class DefensivePlaymakingStat(models.Model):
    player = models.CharField(max_length=120, blank=False)
    season = models.CharField(max_length=10, blank=False)
    team = models.CharField(max_length=3)
    age = models.IntegerField(default=0)
    height_in = models.IntegerField(default=0)
    weight_lb = models.IntegerField(default=0)
    games_played = models.IntegerField(default=0)
    minutes_played = models.IntegerField(default=0)
    steals = models.IntegerField(default=0)
    blocks = models.IntegerField(default=0)
    deflections = models.IntegerField(default=0)
    charges = models.IntegerField(default=0)
    off_fouls_drawn = models.IntegerField(default=0)
    shooting_fouls = models.IntegerField(default=0)

    rank_per_game_steals = models.FloatField(default=0.0, null=True)
    rank_per_game_blocks = models.FloatField(default=0.0, null=True)
    rank_per_game_deflections = models.FloatField(default=0.0, null=True)
    rank_per_game_stocks = models.FloatField(default=0.0, null=True)
    rank_per_game_deals = models.FloatField(default=0.0, null=True)
    rank_per_game_charges = models.FloatField(default=0.0, null=True)
    rank_per_game_off_fouls_drawn = models.FloatField(default=0.0, null=True)
    rank_per_game_shooting_fouls = models.FloatField(default=0.0, null=True)

    rank_per_min_steals = models.FloatField(default=0.0, null=True)
    rank_per_min_blocks = models.FloatField(default=0.0, null=True)
    rank_per_min_deflections = models.FloatField(default=0.0, null=True)
    rank_per_min_stocks = models.FloatField(default=0.0, null=True)
    rank_per_min_deals = models.FloatField(default=0.0, null=True)
    rank_per_min_charges = models.FloatField(default=0.0, null=True)
    rank_per_min_off_fouls_drawn = models.FloatField(default=0.0, null=True)
    rank_per_min_shooting_fouls = models.FloatField(default=0.0, null=True)

    class Meta:
        unique_together = ('player', 'season')

    def get_height(self):
        return f"{int(self.height_in / 12)}'{self.height_in % 12}"

    def get_deals(self):
        return self.steals + self.deflections

    def get_stocks(self):
        return self.steals + self.blocks

    def __str__(self):
        return f"{self.player} : {self.season}"

justbballstuff/defensive_playmaking/views.py
from django.shortcuts import render
from .tables import TotalDefensivePlaymakingTable, PerGameDefensivePlaymakingTable, PerMinDefensivePlaymakingTable, RankPerGameDefensivePlaymakingTable, RankPerMinDefensivePlaymakingTable
from .filters import DefensivePlaymakingFilter
from .models import DefensivePlaymakingStat
from django_tables2 import SingleTableMixin
from django_filters.views import FilterView

# Create your views here.
class TotalDefensivePlaymakingView(SingleTableMixin, FilterView):
    model = DefensivePlaymakingStat
    table_class = TotalDefensivePlaymakingTable
    template_name = 'defensive_playmaking/table.html'
    filterset_class = DefensivePlaymakingFilter
    extra_context={'title_head': "Defensive Playmaking: Total", "defensive_playmaking": True, "total": True}

class PerGameDefensivePlaymakingView(SingleTableMixin, FilterView):
    model = DefensivePlaymakingStat
    table_class = PerGameDefensivePlaymakingTable
    template_name = 'defensive_playmaking/table.html'
    filterset_class = DefensivePlaymakingFilter
    extra_context={'title_head': "Defensive Playmaking: Per Game", "defensive_playmaking": True, "per_game": True}

class PerMinDefensivePlaymakingView(SingleTableMixin, FilterView):
    model = DefensivePlaymakingStat
    table_class = PerMinDefensivePlaymakingTable
    template_name = 'defensive_playmaking/table.html'
    filterset_class = DefensivePlaymakingFilter
    extra_context={'title_head': "Defensive Playmaking: Per 36 Mins", "defensive_playmaking": True, "per_min": True}

class RankPerGameDefensivePlaymakingView(SingleTableMixin, FilterView):
    model = DefensivePlaymakingStat
    table_class = RankPerGameDefensivePlaymakingTable
    template_name = 'defensive_playmaking/table.html'
    filterset_class = DefensivePlaymakingFilter
    extra_context={'title_head': "Defensive Playmaking: Rank Per Game", "defensive_playmaking": True, "per_game_rank": True}

class RankPerMinDefensivePlaymakingView(SingleTableMixin, FilterView):
    model = DefensivePlaymakingStat
    table_class = RankPerMinDefensivePlaymakingTable
    template_name = 'defensive_playmaking/table.html'
    filterset_class = DefensivePlaymakingFilter
    extra_context={'title_head': "Defensive Playmaking: Rank Per Min", "defensive_playmaking": True, "per_min_rank": True}

def glossary(request):
    return render(request, 'defensive_playmaking/glossary.html', {'title_head': "Defensive Playmaking: Glossary", "defensive_playmaking": True, "glossary": True})

justbballstuff/defensive_playmaking/templates/defensive_playmaking/base.html
{% extends 'justbballstuff/base.html' %}

{% block menu %}
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link {% if total %}active{% endif %}" href="{% url 'defensive_playmaking:total' %}">Total</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if per_game %}active{% endif %}" href="{% url 'defensive_playmaking:per_game' %}">Per Game</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if per_min %}active{% endif %}" href="{% url 'defensive_playmaking:per_min' %}">Per 36</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if per_game_rank %}active{% endif %}" href="{% url 'defensive_playmaking:rank_per_game' %}">Rank Per Game</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if per_min_rank %}active{% endif %}" href="{% url 'defensive_playmaking:rank_per_min' %}">Rank Per 36</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if glossary %}active{% endif %}" href="{% url 'defensive_playmaking:glossary' %}">Glossary</a>
      </li>
    </ul>
  </nav>
{% endblock %}

{% block content %}
{% endblock %}

justbballstuff/defensive_playmaking/templates/defensive_playmaking/glossary.html
{% extends "defensive_playmaking/base.html" %}

{% block content %}
  <h1>Glossary</h1>
  <p>Stats are provided in:</p>
  <ul>
    <li>Season Totals</li>
    <li>Per Games</li>
    <li>Per 36 Minutes</li>
    <li>Percentiles for Per Games for Players who played Minimum 500 Minutes (Rank Per Game)</li>
    <li>Percentiles for Per 36 Minutes for Players who played Minimum 500 Minutes (Rank Per 36)</li>
  </ul>
  <table class="table table-striped">
    <tr>
      <th>PLAYER</th>
      <td>Name of the Player</td>
    </tr>
    <tr>
      <th>TEAM</th>
      <td>Acronym of Team of the Player<br>TEAM is whatever team the player finished the season with (according to https://www.nba.com/stats/players/bio/ at least).</td>
    </tr>
    <tr>
      <th>AGE</th>
      <td>Age of the Player at the Start of that Season</td>
    </tr>
    <tr>
      <th>HEIGHT</th>
      <td>Height of the Player in feet and inches</td>
    </tr>
    <tr>
      <th>WEIGHT</th>
      <td>Weight of the Player in pounds</td>
    </tr>
    <tr>
      <th>SEASON</th>
      <td>Regular Season</td>
    </tr>
    <tr>
      <th>GP</th>
      <td>the Number of Games Played in that Season</td>
    </tr>
    <tr>
      <th>MP</th>
      <td>the Number of Minutes Played in that Season</td>
    </tr>
    <tr>
      <th>STL</th>
      <td>Steals</td>
    </tr>
    <tr>
      <th>BLK</th>
      <td>Blocks</td>
    </tr>
    <tr>
      <th>DEFLECTIONS</th>
      <td>Deflections</td>
    </tr>
    <tr>
      <th>STOCKS</th>
      <td>Steals + Blocks: <code>STL + BLK</code><br>no, I did not make that term up but I don't know of too many people that have quanitified this frequently discussed term.</td>
    </tr>
    <tr>
      <th>DEALS</th>
      <td>Deflections + Steals: <code>Deflections + STL</code><br>I think I made this term up unless someone beat me to it. clever, corny? maybe both? you be the judge</td>
    </tr>
    <tr>
      <th>CHARGES</th>
      <td>Charges Drawn</td>
    </tr>
    <tr>
      <th>OFF FOULS DRAWN</th>
      <td>Offensive Fouls Drawn (per basketball-reference)</td>
    </tr>
    <tr>
      <th>SHOOTING FOULS</th>
      <td>Shooting Fouls Committed (per basketball-reference)</td>
    </tr>
  </table>
{% endblock %}

justbballstuff/defensive_playmaking/templates/defensive_playmaking/table.html
{% extends "defensive_playmaking/base.html" %}
{% load render_table from django_tables2 %}
{% load bootstrap4 %}

{% block content %}
  <h4 class='display-4'>{{ title_head }}</h4>
  <p>Get steals, blocks, deflections, stocks (steals + blocks), deals (deflections + steals), charges drawn, offensive fouls drawn, and shooting fouls since 2017-18..  Stats come in Total, Per Game, and Per 36 Minutes, alonged with rank percentiles for players who played at least 500 minutes.</p>
  {% include 'defensive_playmaking/filters.html' %}
  {% render_table table %}
{% endblock %}