justbballstuff/justbballstuff/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('profiles/', include('player_profile.urls')),
    path('matchups/', include('matchups.urls')),
    path('defensive-playmaking/', include('defensive_playmaking.urls')),
    path('rim-protection/', include('rim_protection.urls')),
    path('defensive-synergy/', include('defense_synergy.urls')),
    path('defensive-rebounding/', include('defensive_rebounding.urls')),
]

justbballstuff/rim_protection/urls.py
from django.urls import path
from . import views

app_name = 'rim_protection'

urlpatterns = [
    path('total/', views.TotalRimProtectionView.as_view(), name='total'),
    path('per-game/', views.PerGameRimProtectionView.as_view(), name='per_game'),
    path('per-36/', views.PerMinRimProtectionView.as_view(), name='per_min'),
    path('glossary/', views.glossary, name='glossary'),
]

justbballstuff/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('matchups/', include('matchups.urls')),
    path('defensive-playmaking/', include('defensive_playmaking.urls')),
    path('defensive-synergy/', include('defense_synergy.urls')),
    path('rim-protection/', include('rim_protection.urls')),
    path('defensive-rebounding/', include('defensive_rebounding.urls')),
]

justbballstuff/rim_protection/models.py
from django.db import models

# Create your models here.
class RimProtectionStat(models.Model):
    player = models.CharField(max_length=120, blank=False)
    season = models.CharField(max_length=10, blank=False)
    team = models.CharField(max_length=3)
    age = models.IntegerField(default=0)
    height_in = models.IntegerField(default=0)
    weight_lb = models.IntegerField(default=0)
    games_played = models.IntegerField(default=0)
    minutes_played = models.IntegerField(default=0)
    freq = models.FloatField(default=0.0)
    def_fgm = models.IntegerField(default=0)
    def_fga = models.IntegerField(default=0)
    def_fg_pct = models.FloatField(default=0.0)
    def_fg_pct_score = models.FloatField(default=0.0, null=True)
    diff_fg_pct = models.FloatField(default=0.0)
    diff_fg_pct_score = models.FloatField(default=0.0, null=True)
    def_fgm_per_game = models.FloatField(default=0.0)
    def_fga_per_game = models.FloatField(default=0.0)
    def_fgm_per_min = models.FloatField(default=0.0)
    def_fga_per_min = models.FloatField(default=0.0)

    class Meta:
        unique_together = ('player', 'season')

    def get_height(self):
        return f"{int(self.height_in / 12)}'{self.height_in % 12}"

    def __str__(self):
        return f"{self.player} : {self.season}"

justbballstuff/rim_protection/views.py
from django.shortcuts import render
from .tables import TotalRimProtectionTable, PerGameRimProtectionTable, PerMinRimProtectionTable
from .filters import RimProtectionFilter
from .models import RimProtectionStat
from django_tables2 import SingleTableMixin
from django_filters.views import FilterView

# Create your views here.
class TotalRimProtectionView(SingleTableMixin, FilterView):
    model = RimProtectionStat
    table_class = TotalRimProtectionTable
    template_name = 'rim_protection/table.html'
    filterset_class = RimProtectionFilter
    extra_context={'title_head': "Rim Protection: Total", "rim_protection": True, "total": True}

class PerGameRimProtectionView(SingleTableMixin, FilterView):
    model = RimProtectionStat
    table_class = PerGameRimProtectionTable
    template_name = 'rim_protection/table.html'
    filterset_class = RimProtectionFilter
    extra_context={'title_head': "Rim Protection: Per Game", "rim_protection": True, "per_game": True}

class PerMinRimProtectionView(SingleTableMixin, FilterView):
    model = RimProtectionStat
    table_class = PerMinRimProtectionTable
    template_name = 'rim_protection/table.html'
    filterset_class = RimProtectionFilter
    extra_context={'title_head': "Rim Protection: Per 36 Mins", "rim_protection": True, "per_min": True}

def glossary(request):
    return render(request, 'rim_protection/glossary.html', {'title_head': "Rim Protection: Glossary", "rim_protection": True, "glossary": True})

justbballstuff/rim_protection/templates/rim_protection/base.html
{% extends 'justbballstuff/base.html' %}

{% block menu %}
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link {% if total %}active{% endif %}" href="{% url 'rim_protection:total' %}">Total</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if per_game %}active{% endif %}" href="{% url 'rim_protection:per_game' %}">Per Game</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if per_min %}active{% endif %}" href="{% url 'rim_protection:per_min' %}">Per 36</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if glossary %}active{% endif %}" href="{% url 'rim_protection:glossary' %}">Glossary</a>
      </li>
    </ul>
  </nav>
{% endblock %}

{% block content %}
{% endblock %}

justbballstuff/rim_protection/templates/rim_protection/glossary.html
{% extends "rim_protection/base.html" %}

{% block content %}
  <h1>Glossary</h1>
  <p class="alert alert-danger">Please Note: These stats are only recorded for non-guards who defend at least 30% of their contested shots at the rim (less than 6 feet). Rim protection from guards/wings is still an important concept, it just comes in other/much-harder-to-quantify forms: good rotational defense from good stunts to deter drives, tagging rollers, sinking in to cover unguarded lob threats, and good on-ball defense like containing drives one-on-one or being smart in how you navigate on ball and off ball screens.  Second, these stats do not encompass all of rim protection as a whole even for bigs.  These stats do no quantify the ability to deter shots at the rim which is an extremely important concept of rim protection as a whole.  These stats do no quantify how well you defend shots at the rim without fouling which is a really important concept of rim protection as a whole.  That said, these stats do effectively capture how well they contest shots at the rim, just don't let it be the finish line in the discourse.</p>

  <p>Stats are provided in:</p>
  <ul>
    <li>Season Totals</li>
    <li>Per Games</li>
    <li>Per 36 Minutes</li>
  </ul>
  <table class="table table-striped">
    <tr>
      <th>PLAYER</th>
      <td>Name of the Player</td>
    </tr>
    <tr>
      <th>TEAM</th>
      <td>Acronym of Team of the Player<br>TEAM is whatever team the player finished the season with (according to https://www.nba.com/stats/players/bio/ at least).</td>
    </tr>
    <tr>
      <th>AGE</th>
      <td>Age of the Player at the Start of that Season</td>
    </tr>
    <tr>
      <th>HEIGHT</th>
      <td>Height of the Player in feet and inches</td>
    </tr>
    <tr>
      <th>WEIGHT</th>
      <td>Weight of the Player in pounds</td>
    </tr>
    <tr>
      <th>SEASON</th>
      <td>Regular Season</td>
    </tr>
    <tr>
      <th>GP</th>
      <td>the Number of Games Played in that Season</td>
    </tr>
    <tr>
      <th>MP</th>
      <td>the Number of Minutes Played in that Season</td>
    </tr>
    <tr>
      <th>FREQ%</th>
      <td>of all Field Goal Attempts contested, how many of them were within 6 feet of the rim</td>
    </tr>
    <tr>
      <th>DFGM</th>
      <td>Of All Field Goal Attempts contested within 6 feet of the rim, how field goal attempts were made</td>
    </tr>
    <tr>
      <th>DFGA</th>
      <td>How Many Field Goal Attempts Contested With in 6 feet of the Rim</td>
    </tr>
    <tr>
      <th>DFG%</th>
      <td>the FG% of shots contested within 6 feet of the rim</td>
    </tr>
    <tr>
      <th>DFG% SCORE</th>
      <td>the DFG% percentile among players who played at least 500 minutes </td>
    </tr>
    <tr>
      <th>Diff%</th>
      <td>the difference in actual FG% of shots conested at the rim and predicted FG% of shots contested within 6 feet of the rim</td>
    </tr>
    <tr>
      <th>Diff% SCORE</th>
      <td>the Diff% percentile among players who played at least 500 minutes </td>
    </tr>
  </table>
{% endblock %}

justbballstuff/rim_protection/templates/rim_protection/table.html
{% extends "rim_protection/base.html" %}
{% load render_table from django_tables2 %}
{% load bootstrap4 %}

{% block content %}
  <h4 class='display-4'>{{ title_head }}</h4>
  <p>Get defended FG% within 6 feet of the rim along with the difference between FG% allowed at the rim versus expected FG% for every non-guard that defends at least 30% of their contested shots at the rim.  Stats come in Total, Per Game, and Per 36 Minutes, alonged with rank percentiles for players who played at least 500 minutes.</p>
  {% include 'rim_protection/filters.html' %}
  {% render_table table %}
{% endblock %}